[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
good_lp = { version = "1.14.2", default-features = false, features = ["highs"] }
image = "0.25.9"
itertools = "0.14.0"
regex = "1.12.2"
